# Generated by Django 4.1.2 on 2022-11-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=120),
        ),
    ]
