# Generated by Django 4.1.2 on 2022-11-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_login_password_login_name_login_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Logins',
        ),
    ]
