# Generated by Django 4.1.2 on 2022-11-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_login_logins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logins',
            name='phone',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
