# Generated by Django 4.1.2 on 2022-12-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_login_delete_logins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='s_speed',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
