# Generated by Django 4.1.4 on 2023-01-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_login_s_speed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=15)),
                ("speed", models.IntegerField()),
            ],
        ),
    ]
