# Generated by Django 4.1.4 on 2023-01-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_speed"),
    ]

    operations = [
        migrations.AddField(
            model_name="speed",
            name="s_speed",
            field=models.IntegerField(null=True),
        ),
    ]
